# ===== НАСТРОЙКА ПОЧТЫ (MAIL.RU) =====
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=notifyi@mail.ru
spring.mail.password=RJjlv9uRYHnqMX9OMJWf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===== ПОРТ СЕРВЕРА =====
server.port=8080

# ===== РАЗМЕР ФАЙЛОВ =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Настройки Redis (для Docker)
spring.data.redis.host=redis
spring.data.redis.port=6379

# Таймауты
spring.data.redis.timeout=5000ms
spring.data.redis.connect-timeout=5000ms
